CREATE DATABASE IF NOT EXISTS AURORA_LAB_DB;
CREATE SCHEMA IF NOT EXISTS AURORA_LAB_DB.AURORA_LAB_SCHEMA;

USE DATABASE AURORA_LAB_DB;
USE SCHEMA AURORA_LAB_SCHEMA;

CREATE TABLE IF NOT EXISTS DOCUMENTS (
  DOC_ID STRING,
  SOURCE_ID STRING,
  SOURCE_VERSION STRING,
  SOURCE_TYPE STRING,
  SOURCE_URI STRING,
  TITLE STRING,
  LANGUAGE STRING,
  SUMMARY_SHORT STRING,
  SUMMARY_LONG STRING,
  METADATA VARIANT,
  CREATED_AT TIMESTAMP_NTZ
);

CREATE TABLE IF NOT EXISTS KB_SEGMENTS (
  DOC_ID STRING,
  SEGMENT_ID STRING,
  START_MS NUMBER,
  END_MS NUMBER,
  SPEAKER STRING,
  TEXT STRING,
  TOPICS ARRAY,
  ENTITIES ARRAY,
  SOURCE_REFS VARIANT,
  UPDATED_AT TIMESTAMP_NTZ
);

CREATE TABLE IF NOT EXISTS ENTITIES (
  ENTITY_ID STRING,
  NAME STRING,
  TYPE STRING,
  ALIASES ARRAY,
  METADATA VARIANT,
  UPDATED_AT TIMESTAMP_NTZ
);

CREATE TABLE IF NOT EXISTS RELATIONS (
  REL_ID STRING,
  SUBJ_ENTITY_ID STRING,
  PREDICATE STRING,
  OBJ_ENTITY_ID STRING,
  DOC_ID STRING,
  SEGMENT_ID STRING,
  CONFIDENCE NUMBER,
  UPDATED_AT TIMESTAMP_NTZ
);

CREATE TABLE IF NOT EXISTS ONTOLOGY (
  PREDICATE STRING,
  DOMAIN_TYPE STRING,
  RANGE_TYPE STRING,
  DESCRIPTION STRING,
  UPDATED_AT TIMESTAMP_NTZ
);

CREATE TABLE IF NOT EXISTS CLAIMS (
  CLAIM_ID STRING,
  CLAIM_TEXT STRING,
  DOC_ID STRING,
  SEGMENT_ID STRING,
  CONFIDENCE NUMBER,
  UPDATED_AT TIMESTAMP_NTZ
);

CREATE TABLE IF NOT EXISTS MEMORY (
  MEMORY_ID STRING,
  CATEGORY STRING,
  TEXT STRING,
  TOPICS ARRAY,
  ENTITIES ARRAY,
  SOURCE_REFS VARIANT,
  CREATED_AT TIMESTAMP_NTZ
);

CREATE TABLE IF NOT EXISTS INITIATIVES (
  INITIATIVE_ID STRING,
  TITLE STRING,
  SCORES VARIANT,
  OVERALL_SCORE NUMBER,
  RATIONALE STRING,
  CITATIONS VARIANT,
  UPDATED_AT TIMESTAMP_NTZ
);

CREATE TABLE IF NOT EXISTS INITIATIVE_REPORTS (
  REPORT_ID STRING,
  REPORT_TEXT STRING,
  CREATED_AT TIMESTAMP_NTZ
);
